name: Update views_pipeline on Changes in cm_querysets.py and pgm_querysets.py

# Trigger on file changes in viewsforecasting
on:
  push:
    branches:
      - main
      - github_workflows
    paths:
      - Tools/cm_querysets.py
      - Tools/pgm_querysets.py
  workflow_dispatch:

jobs:
  modify-views_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout viewsforecasting repository
      uses: actions/checkout@v3
      with:
        repository: prio-data/viewsforecasting
        token: ${{ secrets.VIEWS_PIPELINE_ACCESS_TOKEN }}

    - name: Clone views_pipeline repository
      run: |
        git clone https://github.com/prio-data/views_pipeline.git
        cd views_pipeline
        git checkout create_cm_catalog_01

    - name: Clone viewsforecasting repository 
      run: |
        cd views_pipeline
        git clone https://github.com/prio-data/viewsforecasting.git ../viewsforecasting

    - name: Run Python script  
      run: |
        cd views_pipeline
        python documentation/catalogs/generate_links_to_querysets.py

    - name: Commit and Push Changes
      run: |
        cd views_pipeline
        git add documentation/catalogs/cm_model_catalog.md
        git commit -m "Automated changes by GitHub Actions"
        git push origin create_cm_catalog_01
      env:
        GITHUB_TOKEN: ${{ secrets.VIEWS_PIPELINE_ACCESS_TOKEN }}


