name: dispatch event to views_pipeline on changes in cm_querysets.py and pgm_querysets.py

# Trigger on file changes in viewsforecasting
on:
  push:
    branches:
      - main
      - github_workflows
    paths:
      - Tools/cm_querysets.py
      - Tools/pgm_querysets.py

jobs:
  modify-views_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout views_pipeline repository
      uses: actions/checkout@v3
      with:
        repository: lujzi05/views_pipeline
        token: ${{ secrets.VIEWS_PIPELINE_ACCESS_TOKEN }}

    - name: Clone viewsforecasting repository
      run: |
        git clone https://github.com/your_username/lujzi05/views_pipeline.git
        cd views_pipeline
        git checkout create_cm_catalog_01

    - name: Run Python script  
      run: |
        python documentation/catalogs/generate_links_to_querysets.py

    - name: Commit and Push Changes
      run: |
        git add documentation/catalogs/cm_model_catalog.md
        git commit -m "Automated changes by GitHub Actions"
        git push origin create_cm_catalog_01
      env:
        GITHUB_TOKEN: ${{ secrets.VIEWS_PIPELINE_ACCESS_TOKEN }}


